# Generated by Django 4.2.3 on 2023-07-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
