# Generated by Django 4.2.3 on 2023-07-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_course_options_remove_course_lessons_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Курс'),
        ),
    ]
