# Generated by Django 4.2.3 on 2023-07-14 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_lesson_course_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='paid_course_or_lesson',
        ),
        migrations.AddField(
            model_name='payments',
            name='paid_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Оплаченный курс'),
        ),
        migrations.AddField(
            model_name='payments',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.lesson', verbose_name='Оплаченный урок'),
        ),
    ]
