# Generated by Django 4.2.3 on 2023-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое урока'),
        ),
    ]
