# Generated by Django 4.2.3 on 2023-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_coursesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID платежа в Stripe'),
        ),
    ]
