# Generated by Django 4.2.3 on 2023-07-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_payments_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_intent_id',
        ),
    ]
